### PR TITLE
Tsc 470 search tab improvements

### PR DESCRIPTION
**Pull request by jay-jhk-lee**
moved center and extend column next to the status column
changed time display to look informational rather than editable
added label to time display
reduced padding and moved subheader to fixed header to make results more vertically compact

Screen Shot 2024-08-05 at 4 29 05 PM
Screen Shot 2024-08-05 at 4 28 55 PM

### CODE REVIEW

**Comment by paologum** [comment]
center the empty dashed lines in `center` and `expand` so they align with the icons

**Comment by paologum** [comment]
also to make it easier to read, make the time settings display at the top a grid or a flex thing so that the units are aligned column wise and the top/base are aligned column wise

**Comment by jay-jhk-lee** [comment]
image

**Comment by paologum** [comment]
`setup-preview` is not working so, did you center the dashes 

image

**Comment by jay-jhk-lee** [comment]
image

**Review by paologum — APPROVED** [review]

**Pull request merged**
