### PR TITLE
fixed age popup not showing

### PR DESCRIPTION
**Pull request by asivath**
image
image

Removed generateChart from general-actions.ts and made Home.tsx use initiateChartGeneration

### CODE REVIEW

**Review by paologum — CHANGES_REQUESTED** [review]
this is more of a general comment but the way the popup shows right now feels really weird

can you format it similar to this

You can use the same buttons but add a thin border to the popup and format the buttons like that 

Also don't have the Age-Flag detected, just ask the simple Do you want to use the default age

image

**Comment by asivath** [comment]
image
image

**Comment by asivath** [comment]
image
image

**Review by paologum — APPROVED** [review]
looks great

**Pull request merged**
