### PR TITLE
reupdate file metadata on use of datapack

### PR DESCRIPTION
**Pull request by paologum**
title

### CODE REVIEW

**Review by JacquiFreeElectron — APPROVED** [review]
looks great

**Review by jay-jhk-lee — APPROVED** [review]
looks good

**Review by asivath — APPROVED** [review]
lgtm idk if you want to include it in this pr but you could send an email saying their datapack is being sunsetted

**Comment by paologum** [comment]
yeah that seems like a good idea, i'll add that to jira for a different task/pr

**Pull request merged**
